CKI-project/tests-beaker

- distribution/kpkginstall/runtest.sh
make targz does not doing anything special for aarch64 either, follow
the ppc64 symlink example.
Signed-off-by: Don Zickus <dzickus@redhat.com>
> Add aarch64 symlink for kernel vmlinux

- distribution/kpkginstall/runtest.sh
Remove the vmlinux file on aarch64 so that the vmlinuz file is used.
> aarch64: Remove vmlinux

- distribution/kpkginstall/runtest.sh
s390 cannot boot from the generic vmlinux file provided by targz-pkg.
Strip the vmlinux properly until the upstream patch can be merged:
https://patchwork.kernel.org/patch/10534813/
> Strip vmlinux for s390

- distribution/ltp/lite/metadata
Especially a problem with PowerVMs when QE is running filesystem tests
on the same LPAR.
> LTP - workaround for slow AI/AD tests

- distribution/ltp/lite/RHELKT1LITE.20180515
Allow the `move_pages12` check to take up to 15 minutes to complete
with a 3x timeout multiplier. This is required for some aarch64 servers
with slow CPUs and very large hugepages.
> move_pages12: Increase timeout multiplier

- distribution/ltp/lite/grab_corefiles.sh
The core files may be dumped because of a problem in kernel, but also
because of a completely unrelated one. Because of the later, we don't
want to report a warning to the developer if a core file is found but
all the tests passed.
Changing only the reported result but keeping the core files in the job
allows for debugging / reporting a problem to unrelated component if
it's needed.
> ltp - report pass with corefiles

- distribution/ltp/lite/RHELKT1LITE.20180515
There's an issue where `exit` is called from the signal handler instead
of `_exit`, making the test run stuck. We should skip the test until the
fix is applied.
> LTP: don't run mmapstress10

- distribution/ltp/lite/patches/ltp-include-relax-timer-thresholds-for-non-baremetal.patch
They often fail with "XXX slept too long". We still want to run these
test to make sure the functionality is OK, so let's try to increase the
time they can take. One of the possible causes why the old thresholds
are not enough anymore are the Spectre/Meltdown patches, since the
number of times these tests started failing increased significantly
after the mitigations were applied.
> Increase the threshold for timing tests on VMs

- distribution/kpkginstall/new-kernel-pkg
- distribution/kpkginstall/runtest.sh
Some RHEL deployments do not have `/sbin/new-kernel-pkg` present.
Ensure that the script is always present and executable.
> Restore new-kernel-pkg

- distribution/ltp/lite/RHELKT1LITE.20180515
See https://github.com/linux-test-project/ltp/issues/407
The test can be re-enabled after the issue is fixed and patch ported.
> LTP: temporarily disable migrate_pages02

- distribution/kpkginstall/runtest.sh
The bugs requiring the workaround for BLS-using systems are fixed now.
> Use the recommended way to set default kernel

- vm/hugepage/libhugetlbfs/KnownIssueList
- vm/hugepage/libhugetlbfs/Makefile
- vm/hugepage/libhugetlbfs/PURPOSE
- vm/hugepage/libhugetlbfs/kvercmp.sh
- vm/hugepage/libhugetlbfs/patches/0001-Defined-task-size-value-to-be-512T-if-it-is-more-tha.patch
- vm/hugepage/libhugetlbfs/patches/0001-Force-text-segment-alignment-to-0x08000000-for-i386-.patch
- vm/hugepage/libhugetlbfs/patches/0001-aarch64-fix-page-size-not-properly-computed.patch
- vm/hugepage/libhugetlbfs/patches/0001-ld.hugetlbfs-arm-arches-fix-page-size-and-text-offse.patch
- vm/hugepage/libhugetlbfs/patches/0001-ld.hugetlbfs-pick-an-emulation-if-m-is-not-present.patch
- vm/hugepage/libhugetlbfs/patches/0001-libhugetlbfs-tests-adding-missing-header-file-falloc.patch
- vm/hugepage/libhugetlbfs/patches/0001-restrict-is-a-reserved-keyword-in-C99.patch
- vm/hugepage/libhugetlbfs/patches/0001-tests-Makefile-HUGELINK_RW_TESTS-not-being-reference.patch
- vm/hugepage/libhugetlbfs/patches/0001-testutils-fix-range_is_mapped.patch
- vm/hugepage/libhugetlbfs/patches/0002-runtests.py-Change-R-to-R-in-elflink_rw_test-functio.patch
- vm/hugepage/libhugetlbfs/patches/0002-stack_grow_into_huge-don-t-clobber-existing-mappings.patch
- vm/hugepage/libhugetlbfs/patches/0003-ld.hugetlbfs-pick-an-emulation-if-m-is-not-present.patch
- vm/hugepage/libhugetlbfs/patches/0004-tests-heapshrink-allocate-enough-to-expand-heap.patch
- vm/hugepage/libhugetlbfs/patches/0005-ld.hugetlbfs-support-512M-hugepages-on-aarch64.patch
- vm/hugepage/libhugetlbfs/patches/assume-support-rhel6.patch
- vm/hugepage/libhugetlbfs/patches/build_flags.patch
- vm/hugepage/libhugetlbfs/patches/fix-plt_extrasz-always-returning-0-on-ppc64le.patch
- vm/hugepage/libhugetlbfs/patches/hack-task-size-overrun.patch
- vm/hugepage/libhugetlbfs/patches/huge_page_setup_helper-do-not-assume-default-huge-pa.patch
- vm/hugepage/libhugetlbfs/patches/huge_page_setup_helper-python3-convert.patch
- vm/hugepage/libhugetlbfs/patches/map_high_truncate.patch
- vm/hugepage/libhugetlbfs/patches/misalign-make-some-adjustments-for-misalign.patch
- vm/hugepage/libhugetlbfs/patches/remove-duplicate-cases.patch
- vm/hugepage/libhugetlbfs/patches/run_tests-python3-convert.patch
- vm/hugepage/libhugetlbfs/patches/tests-linkhuge_rw-function-ptr-may-not-refer-to-.tex.patch
- vm/hugepage/libhugetlbfs/runtest.sh
@spbnick libhugetlbfs has been sanitized and passing reliably on Fedora 28, I'll include a link to the beaker jobs in the jira ticket.
> Libhugetlbfs

- distribution/kpkginstall/runtest.sh
Inability to extract the tarball would most likely indicate lack of disk
space or denied permissions for the user, not a problem with the kernel.
Similarly, having a different kernel booted after the installation
completed could be (and we did run into this situation) caused by a bug
in grub.
We'll be transitioning to treating this task as a normal test. Therefore
the only thing that should report a real failure is a kernel panic
during the boot.
> kpkginstall: abort when the issue is caused by the OS

- distribution/kpkginstall/Makefile
Downloading the tarball can take longer than expected.
> Increase timeout for kpkginstall

- distribution/ltp/lite/configs/RHELKT1LITE.20180926
There is an unresolved issue with the test timeouting on aarch64.
> Temporarily disable migrate_pages03 from running

- filesystems/xfs/xfstests/known_issues
We have the following three cases failing in CKI currently:
generic/084: Seen only once so far, and is related to a real data corruption
generic/139: This one may be related to a test case issue on ppc64le
generic/394: Failed generic/394 because the test filesystem had a dirty log after
unmount. No unmount record appears to be in the log, and xfs_repair
reported the log was dirty. This was seen multiple times so far in CKI.
We have internal tickets to track each case, and each one will be handled separately, we can remove from known_issues file after they've been resolved.
> add generic/084, generic/139, generic/394 to known isssues file

- distribution/ltp/include/knownissue.sh
hi @veruu can we please disable fallocate05 test in ltp on s390x ? See bz or internal ticket for more details.
> disable fallocate05 test on s390x, bug 1657032

- distribution/ltp/lite/configs/RHELKT1LITE.20180926
ptrace07 test will fail on AMD systems, the internal bz was closed
as "CLOSED NOTABUG", the test will need to be updated in order to
workaround it, see internal ticket #409 for more details.
> ltp/lite ptrace07 test failed on AMD system

- distribution/ltp/include/knownissue.sh
fallocate05 started failing on s390x/rhel8 recently, to be safe
lets mark them as known/fatal for all rhel releases for the given
arches.
> Move fallocate05 as a known issue for all rhel releases

- distribution/ltp/lite/runtest.sh
- distribution/ltp/tests.yml
This will enable DCI team to run ltp-lite using the standard test interface, the exit code needs to be set appropriately to allow Ansible to report the result correctly in STI. There is also one additional tests.yml playbook which will be ignored unless running it directly with Ansible.
> Initial commit for ltp-lite standard test interface

- filesystems/loopdev/sanity/Makefile
- filesystems/loopdev/sanity/PURPOSE
- filesystems/loopdev/sanity/runtest.sh
This is to port test case `/kernel/loopdev/sanity` to public repo, and the latest iozone [1] is used. Please help to review, thanks!
[1] http://www.iozone.org/src/current/iozone3_487.tar
> Sanitize sanity test for loop device and move to the public repo

- distribution/kpkginstall/runtest.sh
Kernel versions called "Extracting kernel version from <URL>" aren't
that common...
> Deduplication is nice, but not when we are grabbing the output

- distribution/kpkginstall/runtest.sh
The original code only works if the kernel package has higher version
than the already installed one.
> Add showduplicates option for listing

- distribution/kpkginstall/runtest.sh
Showduplicates is nice to get us older packages than currently installed
kernel. However this means that after the installation, our kernel is
listed both as "installed" and "available" and thus shows up twice in
the version extraction, leading into having a version like
"4.20.8-100.fc28\n4.20.8-100.fc28"; which is not what we want.
> Only list available packages

- distribution/kpkginstall/runtest.sh
On ppc there are somehow KVER quoting issues. This patch fixes it.
> fixup getting kvr

- distribution/ltp/lite/configs/RHELKT1LITE.20190115
hi @veruu I noticed the rhel7 job failed in CI since I forgot to disable in config file as well, it will fail since the file was removed to avoid the compilation errors:
```
+	# work around Bug 1672242 - clash between linux/in.h and netinet/in.h
+	if grep -q "release 7" /etc/redhat-release; then rm -f $(TARGET)/testcases/kernel/syscalls/setsockopt/setsockopt03.c || true; fi
<<<test_start>>>
tag=setsockopt03 stime=1550839174
cmdline="setsockopt03"
contacts=""
analysis=exit
<<<test_output>>>
<<<execution_status>>>
initiation_status="pan(31271): execvp of 'setsockopt03' (tag setsockopt03) failed.  errno:2  No such file or directory"
duration=0 termination_type=exited termination_id=2 corefile=no
cutime=0 cstime=0
<<<test_end>>>
```
> disable setsockopt03 in config as well

- distribution/kpkginstall/runtest.sh
Apparently, the output of yum can sometimes confuse the 'yum list'
command, which is a subject of this patch. We end-up with two lines and
the first is set to KVER, resulting in nonsense.
This patch fixes it.
> fixup kpkginstall in ppc64le

- storage/blk/Makefile
- storage/blk/README.md
- storage/blk/runtest.sh
To finish task FASTMOVING-415, we have to write block tests which focus on block and loop testing.
> FASTMOVING-415 Enable blktests in kpet-db

- distribution/ltp/lite/configs/RHELKT1LITE.20190115
As the reason for CKI is to provide a quick gating test for each
pre-apply patch, so better to run some stable and functional case
in this ltp-lite. Here I just remove many stress and fragile cases
from the runtest file to make ltp-lite has a pretty baseline.
Btw, we will also run the complete ltp-lite in kernel Tier1 and other
deeping test. So we do have lost nothing but just making CKI more faster
and stable.
> reduce the number of ltp-lite case in CKI

- distribution/ltp/include/ltp-make.include
- distribution/ltp/include/patches/20190115/0001-fcntl36-make-sure-write-threads-complete-at-least-1-.patch
- distribution/ltp/include/patches/20190115/0001-syscalls-cma-fix-the-failure-of-compiling-with-O2-op.patch
- distribution/ltp/include/patches/20190115/0001-syscalls-migrate_pages03-skip-migratition-of-shared-.patch
To fix three test failures reported by CKI:
migrate_pages03, fcntl36, process_vm_readv03
> ltp/include: backport patches for test fixing

- vm/kvm-unit-tests/Makefile
If moving to check-install, this will required for kvm-unit-tests if run stand alone.
> enable additional dependencies for kvm-unit-tests

- storage/blk/runtest.sh
These test cases fail randomly, so disable them to get a stable test result.
o blktests/tests/block/009      FAIL
o blktests/tests/block/020      FAIL
o blktests/tests/block/025      FAIL
o blktests/tests/loop/002       FAIL
o blktests/tests/loop/004       FAIL
> disable those test cases failing randomly

- distribution/kpkginstall/Makefile
@veruu this is needed if we move to check-install task otherwise objcopy command isn't found
> missing objcopy command if running check-install

- vm/hugepage/libhugetlbfs/runtest.sh
Here a new bz was opened:
Bug 1656431 - libhugetlbfs "counters" test case is intermittently failing
> libhugetlbfs: Bug 1006253 occured again

- distribution/kpkginstall/runtest.sh
We have COPR repos containing both kernel.ARCH and kernel.src so we get
double output here which we really don't want.
> Check architecture before grabbing kernel version

- kdump/include/runtest.sh
Make the test compatible with fedora kernel.
Sysrq operations have to be enabled on fedora kernel in order to trigger sysrq-c panic.
> kdump: enable sysrq operations

- filesystems/nfs/connectathon/Makefile
Additional dependencies needed if using check-install task
> add git dep for connectathon

- distribution/ltp/include/knownissue.sh
The suffix of kernel version haven't being handled in the kvercmp() funcion,
so we get wrong result in compare the 5.1.0 with 5.1.0-rc2.cki leads to ltp
cann't mask mount02 failure correctly.
In this patch, I just exlarge the RC kernel version to 5.2.0 to make the filter
goes into effect.
> ltp/include: enlarge skipping range for mount02

- packages/perf/internal-testsuite/Makefile
- packages/perf/internal-testsuite/PURPOSE
- packages/perf/internal-testsuite/runtest.sh
- packages/perf/internal-testsuite/white.list
This is a wrapper for perf-test which whitelists some known failures
and unstable tests for the sake of having it stable and passing.
> perf: adding internal-testsuite wrapper for CKI

- stress/stress-ng/runtest.sh
If a stressor causes a kernel panic and reboot, then abort the test
run.  Do not try to start the test again or it will likely get into
a panic-and-reboot-loop until the external watchdog kills it.
> stress/stress-ng: abort if a reboot is detected

- stress/stress-ng/runtest.sh
The `sigsuspend` stressor often locks up systems and the kernel just logs slow path WARNINGs until the test is killed by the watchdog, so add it to the known issues list and skip it.
> stress-ng: add sigsuspend to known issues list

- distribution/ltp/include/knownissue.sh
The function is_upstream() { uname -r | grep -q -v 'el\|fc'; } has problem
to recongise ARK kernel, since CKI build that with suffix *.elrdy.*, here
we just treat it same as upstream kernel.
> ltp/include: treat ARK kernel as upstream too

- stress/stress-ng/runtest.sh
efivar is triggering panics on some x86_64 systems too, so blacklist it for all architectures.
> stress-ng: make efivar a known issue for all arches

- packages/selinux-policy/serge-testsuite/Makefile
- packages/selinux-policy/serge-testsuite/runtest.sh
@veruu this will sync the downstream version with upstream, and allow us to re-enable on s390x & aarch64 on RHEL-8, will test more thoroughly in kpet-db
> update selinux to latest downstream version

- vm/kvm-self-tests/runtest.sh
Previous commit doesn't include the change for rlSkip() ([1]), which should be owing to my mistake in last force push, sorry for the mistake. Hi @rasibley and @veruu,   please help to review and merge it, thanks a lot!
[1] https://github.com/CKI-project/tests-beaker/commit/785bb7eba564722d22d86d711a00a46139b3af17#diff-9b57d0485bf32e366bdeb92a7dfc6f2d
> Enable kvm self tests (#562) (cont)

- packages/perf/internal-testsuite/runtest.sh
updated to skip if kernel-debuginfo is not installed.
> Skip when kernel-debuginfo package is not installed

- distribution/ltp/include/knownissue.sh
As Veronika pointed that the distro exclusion cann't work properly in
upstream kernel testing on RHEL. Becasue sometimes a RHEL kernel bug
maybe has already been fixed in upstream, the distro exclusion still
trying to kick-out it as a known issue.
To solve that we could simply try to detect whether a distro installs the
upstream kernel, if yes, we just give up the filtering rule at this case.
It will be eventually separate the upstream and downstream. Problem could
be located in any part of these: [UPSTREAM] [RHEL8] [RHEL7] [RHEL6] [RHEL5]
Btw, the [UPSTREAM] part includes: CKI, ARK and Mainline kernel.
Note:
osver_in_range is just as workaround for unfix knownissue filtering, once
an unfix problem is being fixed there, we should move it to fixed issue
part and change the rule from distro …
> ltp/include: disable distro exclusion in upstream kernel testing

- stress/stress-ng/Makefile
- stress/stress-ng/runtest.sh
Mustangs have a hardware flaw exposed by stress tests such as stress-ng.  Skip the test if the SUT is a Mustang.
> stress-ng: skip the test on Mustang systems

- distribution/kpkginstall/runtest.sh
We currently download some kernel RPMs from the build repository
but then we don't use those downloaded RPMs for the installation.
We also pick and choose which RPMs to install and this makes it
challenging to add new RPMs later.
Instead, download all of the RPMs that were built and then install
them all from the downloaded copy.
> WIP: Download RPMs and use downloaded RPMs for install

- distribution/ltp/include/knownissue.sh
This will mask the mtest06 on aarch64, see the following for more details:
- https://github.com/linux-test-project/ltp/issues/528
- https://lore.kernel.org/linux-mm/1817839533.20996552.155706544523
> disable mtest06 for ltp-lite upstream kernels

- distribution/ltp/lite/metadata
@veruu this is related to https://github.com/CKI-project/tests-beaker/issues/158, although it will be enforced overall by kpet, these files should still be in sync.
> set metadata test duration to match Makefile

- storage/lvm/thinp/sanity/runtest.sh
If there's not enough space total space on the device, skip the test.
> lvm/thinp/sanity: skip test if not enough space

- distribution/ltp/include/knownissue.sh
@veruu this will mask the ltp failure we are seeing for upstream kernels, we can re-enable once resolved in the ML.
> mask shmctl01 for usptream kernels until resolved

- storage/hba/san-device-stress/Makefile
- storage/hba/san-device-stress/PURPOSE
- storage/hba/san-device-stress/README.md
- storage/hba/san-device-stress/main.sh
- storage/hba/san-device-stress/runtest.sh
a pattern the hba test should be triggered:  
kpet should identify any patches posted to drivers/scsi/lpfc should initiate lpfc testing.  Similarly any patches posted to drivers/scsi/qla2xxx should initiate qla2xxx testing.
Updates to the scsi directory should initiate testing on all scsi
hardware and adapters.
Updates to fc-transport should initiate testing on lpfc and qla2xxx
adapters.
Updates to iscsi infrastructure should initiate testing on iscsi initiators.
Target and other drivers have similar requirements.
> [storage/hba]  add FIO stress tests for HBA regression

- legacy/pci_id/02-pci-id.sh
The first change in the PR fixed kmod search path (as there are debug modules present as well, this was no longer unique).
The second one relaxes the stringent requirement that the set of PCI IDs be equal on a string basis to the requirement that they be syntactically equivalent up to shell pattern expansion (cf. commit message for an example).
Signed-off-by: Cestmir Kalina <ckalina@redhat.com>
> legacy: pci id test changes

- filesystems/xfs/xfstests/install.sh
- filesystems/xfs/xfstests/runtest.sh
It's unnecessary for the tests we are running. Remove sourcing
check.sh by the way as it has been dropped while porting.
> fs/xfs/xfstests: remove install_dbench function

- stress/stress-ng/runtest.sh
The kernel often reports soft lockups during vforkmany on ppc64le systems:
watchdog: BUG: soft lockup - CPU#83 stuck for 22s! [stress-ng-vfork:127885]
> stress-ng: blacklist vforkmany on ppc64le

- stress/stress-ng/runtest.sh
The beakerlib functions like rlDie and rlAssert* report a FAIL or WARN
status, but we want it to be ABORT, so use the rhts-abort command
instead of a beakerlib function.
> stress-ng: use rhts-abort to abort

- filesystems/xfs/xfstests/install.sh
We may installed a wrong package with a name fio but not the one
we want to install. Also fixed the upstream build log.
> filesystems/xfs/xfstests/install.sh: fix install fio

- distribution/kpkginstall/runtest.sh
The comment says we should report a failure and abort but no failure was
actually reported here. Fix it.
> Report a failure if the kernel doesn't install

- legacy/shared/rpm-utils.sh
Due to differences in OS releases, kernel-modules{,-extra} might not be
present. Remedy that by first checking whether or not given package is
available prior to install/unpack attempts.
> legacy: Add RPM package presence checks

- vm/kvm-unit-tests/runtest.sh
The ARM Apollo Hardware has a different signature in journalctl/dmesg to detect KVM initialization.
Update the regular expression to account for that to enable Apollo hardware to run KVM Unit Tests.
Tests ran on Apollo hardware:
aarch64: https://beaker.engineering.redhat.com/jobs/3586593
> Mcondotta arm apollo

- vm/kvm-unit-tests/runtest.sh
The run_test.sh which triggers the KVM Unit Tests was only prepared for RHEL8.0 provisioned systems. The way it was fixing the python symlink did not work for RHEL8.1.
Fixed it to work for any RHEL8.X system. Failure to create the symlink cause all KVM Unit Tests to fail.
Test job:
aarch64: https://beaker.engineering.redhat.com/jobs/3590376
> Fix python for RHEL8.1.

- misc/module-load/modules.f18
- misc/module-load/modules.rhel6
- misc/module-load/modules.rhel7
nfnetlink_log and ipt_ULOG can conflict with each other, so remove
ipt_ULOG from the list.  (RHBZ#1716856)
> module-load: remove ipt_ULOG from the module list

- distribution/kernel-fips-mode/Makefile
- distribution/kernel-fips-mode/PURPOSE
- distribution/kernel-fips-mode/README.md
- distribution/kernel-fips-mode/runtest.sh
Test for kernel FIPS mode. It is applicable for RHEL-8 only and it might be potentially destructive. Any kernel FIPS issue might cause kernel panic and break subsequent testing. Therefore it is important to run this test either in separation or as the last test.
Signed-off-by: Ondrej Moris <omoris@redhat.com>
> distribution/kernel-fips-mode: add test for kernel FIPS mode

- kdump/include/runtest.sh
Fedora or upstream kernel doesn't support crashkernel=auto. Setting crashkernel to 160M may cause kdump kernel OOM on large machines. So setting it to a range instead. The range is same as how crashkernel=auto works on rhel kernels.
> kdump/include: Setting crashkernel mem to a range 

- legacy/pci_id/02-pci-id.sh
- legacy/pci_id/Makefile
- legacy/shared/rpm-utils.sh
- legacy/whitelist/Makefile
- Nightly repository is required for proper baseline comparison.
- Add `yum-utils` requires -- use yumdownloader instead of `(yum|dnf) ([re]install|update) --downloadonly` -- simplifies RPM download code
- Also add kernel package as a source for kernel modules for RHEL7.
> legacy: Use nightly repo for pci id/kabi-whitelist checks, add RHEL7-specific package for pci id comparison

- storage/include/libbkrm.sh
- storage/include/libdebug.sh
- storage/include/libstqe.sh
- storage/iscsi/params/Makefile
- storage/iscsi/params/PURPOSE
- storage/iscsi/params/README.md
- storage/iscsi/params/runtest.sh
`iscsi/params` test case is for testing targetcli by leveraging `https://gitlab.com/rh-kernel-stqe/python-stqe`, please help to review, thanks!
> Add iscsi/params test (#827)

- storage/include/libbkrm.sh
- storage/include/libstqe.sh
For RHEL7, use python2 instead because python3 is not available by default
> Add iscsi/params test case (#827) (cont)

- filesystems/xfs/xfstests/RUNTESTS
- filesystems/xfs/xfstests/xfstests-run.sh
Remove 2 testcases that has been renamed upstream.
> fs/xfs/xfstests: do not report failure if subcase does not exist

- storage/blk/runtest.sh
upstream link:
https://lore.kernel.org/linux-block/e84b29e1-209e-d598-0828-bed5e3b98093@acm.org/
> blktests: disable block/002 due to test case issue.

- cpu/common/libutil.sh
- cpu/driver/Makefile
- cpu/driver/PURPOSE
- cpu/driver/README.md
- cpu/driver/runtest.sh
The test only supports Intel CPU because utility `msr-tools` is a must. And test is unsupported in kvm, e.g.
```bash
root# virt-what 
kvm
root# rdmsr 0x606
rdmsr: CPU 0 cannot read MSR 0x00000606
```
> Add CPU Freq Driver Test (x86_64 only) (#923)

- packages/perf/internal-testsuite/white.list
Handling known failures for perf after syncing with upstream v5.0.
> perf: updating whitelists for internal-testsuite

- packages/perf/perftool-testsuite/Makefile
- packages/perf/perftool-testsuite/PURPOSE
- packages/perf/perftool-testsuite/blacklist.sh
- packages/perf/perftool-testsuite/runtest.sh
The perftool-testsuite should become a part of CKI perf testing as well.
It provides a different approach of perf testing than the internal-testsuite.
The wrapper is based on the wrapper used at Red Hat, but adjusted for the
CKI usage. It contains a blacklist to mask out known issues and unstable
tests, since CI should be stable.
> perf: adding a new testsuite (wrapper)

- kdump/include/runtest.sh
- kdump/kdump-sysrq-c/runtest.sh
kernel-debuginfo package cannot be installed from a yum source if the kernel is installed from a tar.gz.
In this case, the "/usr/lib/debug/lib/modules/$(uname -r)/vmlinux" is supposed to be taken care by cki boot test. Then kdump-sysrq-c will only check if the file exists.
> kdump-sysrq-c: Check kernel debuginfo vmlinux file

- misc/kernel-fips-mode/runtest.sh
Workaround for missing hmac on CKI kernels.
> misc/kernel-fips-mode: workaround for missing hmac on CKI kernels

- misc/kernel-fips-mode/runtest.sh
Tes in kpet-db testing pipeline revealed minor issue, this patch should correct it.
Signed-off-by: Ondrej Moris <omoris@redhat.com>
> misc/kernel-fips-mode: fix hmac files

- packages/redhat-rpm-config/detect-kabi-provides/symvers-foo.spec
As there might be multiple kernels installed, ensure that the currently
running kernel's Module.symvers file is used (i.e., the tested one).
> redhat-rpm-config/detect-kabi-provides: Module.symvers search change

- distribution/kernel-debuginfo/Makefile
- distribution/kernel-debuginfo/runtest.sh
Make sure that kernel-debuginfo vmlinux's .debug* sections are not
accidentally stripped during compile time, as this adversely affects
tracing tools.
> distribution/kernel-debuginfo: Add regression test

- storage/blk/runtest.sh
> blktests: disable nvme test case for upstream 5.0+ aarch64 kernel

- cpu/common/libbkrm.sh
- cpu/common/libutil.sh
- cpu/driver/runtest.sh
- cpu/idle/runtest.sh
- power-management/rapl/powercap/Makefile
- power-management/rapl/powercap/PURPOSE
- power-management/rapl/powercap/README.md
- power-management/rapl/powercap/runtest.sh
This is the 1st PR of ticket `FASTMOVING-1017`, the source code saved in `tests/kernel` includes 7 small shell scripts, I converted them to functions being saved into `runtest.sh` to make things simple and achieve better readability.
A manual test on RHEL8/x86_64 is done, here is the test log:
- http://pastebin.test.redhat.com/781779
> Port test case 'power-management/rapl/powercap' (#1017)

- kernel/ftrace/tracer/Makefile
- kernel/ftrace/tracer/PURPOSE
- kernel/ftrace/tracer/ftrace-tracer.sh
- kernel/ftrace/tracer/include
- kernel/ftrace/tracer/metadata
- kernel/ftrace/tracer/runtest.sh
- kernel/include/shunit2
Ported from
https://github.com/sztsian/kernel-sanity/tree/master/ftrace-tracer
This test enables each ftrace tracer and then disable it.
Tracers should be able to be enabled, and no hang or panic should happen.
> Add ftrace-tracer

- stress/stress-ng/runtest.sh
Older RHEL releases do not have systemd-coredump.socket, so the
systemctl mask command fails which gives bad Beaker test results.
Check if the socket exists before trying to mask/unmask it.
> stress-ng: check if systemd-coredump.socket exists first

- vm/kvm-unit-tests/Makefile
If `/usr/bin/nc` is not present, the following error appears during testing:
```
run_migration timeout -k 1s --foreground 90s /usr/libexec/qemu-kvm -nodefaults -machine pseries,accel=kvm -bios powerpc/boot_rom.bin -display none -serial stdio -kernel powerpc/sprs.elf -smp 1 -append -w # -initrd /tmp/tmp.XCtZmrEE9W
run_migration needs nc (netcat)
```
`nmap-ncat` appears to the correct package on RHEL 7, RHEL 8, and Fedora 30.
> Add nmap-ncat for KVM unit tests

- container/podman/runtest.sh
This PR adds initial RHEL 8 support for the podman system integration test and fixes some warnings from `shellcheck`.
> Add RHEL 8 support for podman test

- vm/kvm-self-tests/patches/bitmap.h.patch
- vm/kvm-self-tests/runtest.sh
This patch will enable CKI to run KVM Self Tests for Kernels that are older than 4.18.0-97 (that do not contain the KVM code rebase).
> vm/kvm-self-tests: Add the patch back for building Kernel Self Tests for older versions (prior to .97, RHEL 8.0.X)

- vm/kvm-self-tests/runtest.sh
Enable KVM Selft Tests to run on all architectures (x86_64, aarch64, s390x, ppc64le).
The kernel code needed to run the tests on s390x and aarch64 is almost merged. This change will allow us to enable these tests as soon as the code is merged in.
> vm/kvm-self-tests: Enable KVM Self Tests to run on all architectures

- storage/blk/runtest.sh
> blktests: disable nvme/* for RHEL8 ppc64le

- storage/include/libstqe.sh
libstqe: Change STQE_STABLE_VERSION to apply fix for python-stqe installation on Fedora
Signed-off-by: Filip Suba <fsuba@redhat.com>
> libstqe: Change STQE_STABLE_VERSION to apply fix for python-stqe

- storage/blk/runtest.sh
> blktests: disable nvme/* for RHEL-8.0.0.z ppc64le/x86_64 and

- cpu/driver/Makefile
- power-management/cpupower/sanity/Makefile
- power-management/rapl/powercap/Makefile
Command 'virt-what' is not found because the related package is missing, so add it to Makefiles.
> Add package 'virt-what' to Makefiles

- cpu/driver/Makefile
- cpu/driver/runtest.sh
Extended the timeout to 30m and also copied the fix from [Rachel's branch](https://github.com/CKI-project/tests-beaker/compare/master...rasibley:cpu_driver_fix?expand=1).
> cpu frequency driver test only runs setup phase on certain jobs (#1098)

- packages/perf/perftool-testsuite/runtest.sh
The perftool-testsuite now supports three runmodes which differ in which
testcases are run and how deep the testsuite does the testing.
BASIC mode is designed for CI. STANDARD mode for normal testing and
EXPERIMENTAL mode is for playing with unstable tests. This should prevent
CKI from failing due to new unstable tests added to the testsuite, like
it happened recently with perf-script tests.
> perf/perftool-testsuite: adoption of the upstream new runmode model

- storage/blk/runtest.sh
upstream blktests have some update which may fix the test case issue, so
re-add the test case
> blktests: remove the blacklisted nvme/ test case

- storage/blk/runtest.sh
Will re-enable it after the issue fixed
> blktests: blacklist nvme/004 for RHEL8 on ppc64le

- networking/udp/udp_socket/runtest.sh
If br_netfilter is not loaded, the modprobe -r would fail.
Remove the return value check as we don't care about the result.
Signed-off-by: Hangbin Liu <liuhangbin@gmail.com>
> networking/udp: do not check the return value for modprobe -r

- vm/kvm-self-tests/runtest.sh
This test was introduced in 4.18.0-128 and is failing on Intel x86_64 machines.
> vm/kvm-self-tests: Disable test vmx_set_nested_state_test for bug 1740235

- cpu/driver/runtest.sh
The default bios configuration on lenovo systems disables HWP and intel_pstate,
as a result the test is currently failing on these systems.  Update the test
to always PASS on lenovo intel based systems.
> Avoid failure for cpu frequency driver test on lenovo intel systems

- distribution/kernel-debuginfo/Makefile
Update test duration to 20 minutes as it can run slower on guest machines and time out.
> update test duration to 20 minutes

- storage/blk/runtest.sh
RHEL-7.2.z/7.3.z/7.4.z:
block/016 block/021 block/023 loop/001 loop/003 loop/005 loop/006
RHEL-7.5.z:
block/021 block/023 loop/001 loop/003 loop/005 loop/006 nvme/006
> blktests: update for RHEL7.2.z/7.3.z/7.4.z/7.5.z

- storage/hba/san-device-stress/Makefile
- storage/hba/san-device-stress/main.sh
Added a function `fio_setup()` to install fio command via its source code if fio is not found on 7.4.z kernel. (BTW, some useless code lines are removed from `main.sh` for better readability.)
> FMK#1071 : storage san device stress test fails on 7.4.z kernel

- packages/perf/internal-testsuite/white.list
"Track with sched_switch" testcase fails in a strange way. It should
not block CKI.
> perf: updating whitelists for internal-testsuite v3

- vm/kvm-self-tests/runtest.sh
1741201: Disable test dirty_log_test on Intel Xeon E3 processors
1741347: Disable test state_test and smm_test on AMD Opteron processors
> vm/kvm-self-tests: Disable tests for bugs 1741201 and 1741347.

- vm/kvm-unit-tests/runtest.sh
- vm/kvm-unit-tests/s390x_unittests.cfg
The sieve test has been failing randomly due to a timeout. This is caused by using zVM configuration (which is slower) instead LPAR for s390x systems.
Updated the commit used for the KVM Unit Tests git repository.
> vm/kvm-unit-tests: Increase the timeout for the sieve test for s390x and update the git commit used.

- iommu/boot/Makefile
- iommu/boot/PURPOSE
- iommu/boot/default-boot-options-amd.txt
- iommu/boot/default-boot-options-intel.txt
- iommu/boot/iommu-dmesg-errors.txt
- iommu/boot/runtest.sh
Add a IOMMU boot test with different parameters. It works on RHEL8, RHEL7, and Fedora 30 at least. It will have to be adapted to work on older RHEL releases due to the use of `journalctl`, though.
> IOMMU boot test

- networking/bridge/sanity_check/runtest.sh
remaining dummy interface would cause driver-sanity fail, so clean up dummy used in bridge test
> networking: clean up dummy interface after bridge test

- vm/kvm-self-tests/runtest.sh
Due to https://bugzilla.redhat.com/show_bug.cgi?id=1741347
These tests have already been disabled for older AMD processors.
> vm/kvm-self-tests: Disable tests for older Intel processors

- distribution/kpkginstall/runtest.sh
We never submit the log referenced by `$OUTPUTFILE`, so we can remove
those references. The main `taskout.log` is enough for kpkginstall.
> Remove references to OUTPUTFILE

- distribution/ltp-upstream/include/knownissue.sh
set min_free_kbytes and ksm tests to fatal, add ftrace-stress-test, sync_file_range02, and signal06 to knownissues file
> Make ltp-upstream more stable

- cki_lib/lib.sh
- distribution/kpkginstall/runtest.sh
The kpkginstall output is highly cluttered and confusing to people outside
the CKI group.
Add simple functions for printing messages with different statuses and use
those throughout the script. Also, remove `-x` from the script to reduce
clutter in the output.
> Make kpkginstall messages friendly

- vm/kvm-unit-tests/aarch64_unittests.cfg
- vm/kvm-unit-tests/runtest.sh
- vm/kvm-unit-tests/x86_unittests.cfg
- Re-enable some test. Enable Nested test cases.
- Disable eventinj test that is failing on older Intel processors.
- Increase timeout for vmx_vmcs_shadow_test.
> vm/kvm-unit-tests: Fix a few test issues

- packages/selinux-policy/serge-testsuite/runtest.sh
This patch forward ports the following downstream commits:
960925c8c Sanity/serge-testuite: add PR#58 to fix SCTP test
bb6ddebc8 Sanity/serge-testuite: bump to latest upstream commit
a64c91958 Sanity/serge-testuite: run cgroupfs_label test on RHEL-8
bf74e8e04 Sanity/serge-testsuite: run sctp subtest on RHEL-8
This should mainly fix SCTP test failures on machines with specific configuration such as this one:
https://lore.kernel.org/stable/cki.7A3421D85E.ZU3GZDBBM0@redhat.com/
> serge-testuite: sync with downstream

- distribution/ltp-upstream/include/knownissue.sh
- distribution/ltp-upstream/lite/patches/ltp-include-relax-timer-thresholds-for-non-baremetal.patch
- distribution/ltp-upstream/lite/runtest.sh
Update to a later commit, link known issues, apply patch for non bare-metal machines as timing on systems with shared resources (and high steal time) is not accurate. See J:3771976 for results, one job failed with an intermittent failure, will continue to monitor it.
> add non bare-metal patch and link known issues

- storage/lvm/thinp/sanity/Makefile
loopdev is missing wget dependency which is causing it to abort in all jobs
> add missing wget dependency to loopdev test

- filesystems/loopdev/sanity/Makefile
The Makefile for the loopdev sanity test was using wget, but it wasn't in the test requirements. Add it so that the test can run properly.
> Add missing wget requirement to loopdev sanity test

- vm/kvm-self-tests/Makefile
Add missing rsync dependency for fedora.
> Add rsync dependency to kvm-selftest

- filesystems/nfs/connectathon/runtest.sh
We should skip the testcase for which the server is offline. But for now
we should at least SKIP the test instead of aborting. Yes, it's an infra
failure but it's reoccuring a lot an no testing is executed because the
recipe gets aborted early on.
> Workaround offline NFS servers

- vm/kvm-unit-tests/ppc64le_unittests.cfg
- vm/kvm-unit-tests/runtest.sh
- vm/kvm-unit-tests/x86_unittests.cfg
Disable the access test for x86_64 for failing in Xeon Silver processors.
Disable the h_cede_tm test for PPC64 for failing in 2.3 (pvr 004e 1203) POWER9 processors.
> vm/kvm-unit-tests: Disable tests failing for x86_64 and PPC64.

- storage/dm/common/Makefile
- storage/dm/common/PURPOSE
- storage/dm/common/README.md
- storage/dm/common/runtest.sh
Currently, it fails when running the case via beaker, but it passes if we run it manually. The test maintainer is helping to figure out why, please hold on to review it until I remove WIP.
> FMK-1038 : Enable /kernel/storage/dm/common test in kpet-db

- networking/ipsec/ipsec_basic/ipsec_basic_netns/Makefile
- networking/ipsec/ipsec_basic/ipsec_basic_netns/runtest.sh
commit fbfe522fb40db9d6e1720a5c12d19fa7bfb8e365
Author: Xiumei Mu <xmu@redhat.com>
Date:   Wed Sep 11 16:37:52 2019 +0800
ipsec/ipsec_basic_netns: extend the test time and send less tcp data
This fix is for tcp connection fail on some mahines(Mustangs,aach64)
Signed-off-by: Hangbin Liu <liuhangbin@gmail.com>
> ipsec/ipsec_basic_netns: extend the test time and send less tcp data

- vm/hugepage/libhugetlbfs/Makefile
This case fails on Fedora30/ppc64le because required packages (e.g. wget, patch, gcc ...) are missing. So, the fix is very simple, just add required packages to its Makefile.
> FMK-1004 : libhugetlbfs is failing on Fedora30

- vm/hugepage/libhugetlbfs/Makefile
The previous fix (commit id: 8ad4422) introduced a bug that 32-bit packages are missing if we run it on 64-bit x86 system. Hence, I enhanced the Makefile to support to get the required packages according to processor type (`uname -p`) of system under test.
> FMK-1004 : libhugetlbfs is failing on Fedora30 (cont)

- distribution/ltp-upstream/lite/patches/dynamic_debug_dmesg_check.patch
- distribution/ltp-upstream/lite/runtest.sh
Now that we test debug kernels, the dynamic_debug01 test will fail the dmesg check when grepping for BUG, patch test to only check for BUG vs DEBUG in logs
> patch ltp dynamic_debug grep check

- networking/igmp/conformance/runtest.sh
Remove this part test as it's a stress test and may have influence
to the testing network.
Signed-off-by: Hangbin Liu <liuhangbin@gmail.com>
> networking/igmp: remove igmp_max limit test

- distribution/kpkginstall/runtest.sh
With Fedora testing we may have different kernel and kernel-headers
package. This task expects the same version of these 2 packages, so
kernel-headers isn't installed. This patch tries to remedy that.
> kpkginstall: allow different kernel-headers version

- distribution/ltp-upstream/lite/patches/dynamic_debug_dmesg_check.patch
- distribution/ltp-upstream/lite/patches/oom_aborts_runtest.patch
- distribution/ltp-upstream/lite/runtest.sh
Workaround for oom test killing runtest.sh, also fixing up another patch which used space indentation vs tabs, one more change related to a git clone option which would cause the checkout to sometimes fail, please see J:3823120 for a test job.
> LTP workaround for oom aborting runtest.sh

- distribution/ltp-upstream/lite/runtest.sh
This PR is to re-enable cve tests in LTP, see beaker job 3829635 for results.
> Add back cve tests for LTP

- networking/igmp/conformance/test_tools/offline/sockopt_if.c
This test tries to input a false ifindex and see if kernel replies a
ENODEV error. But sometimes index 50 may exist and the test would fail.
So let extend the index number to a very large and should not exist number.
Signed-off-by: Hangbin Liu <liuhangbin@gmail.com>
> networking/igmp: extend the ifindex to a very large number

- distribution/ltp-upstream/include/knownissue.sh
read_all_sys is triggering hard lockups on mustangs while reading /sys, see https://lore.kernel.org/linux-arm-kernel/1507592549.3785589.1570404050459.JavaMail.zimbra@redhat.com/
See J:3831529, which runs on mustang for test results.
> LTP - disable read_all_sys on aarch64

- storage/hw_raid/Makefile
- storage/hw_raid/PURPOSE
- storage/hw_raid/main.sh
- storage/hw_raid/runtest.sh
- storage/hw_raid/testinfo.desc
Tests created for HW RAID specifically for HPSA and SMARTPQI driver testing. Will be performed on specific servers (storageqe-29 - HPSA and storageqe-32 - SMARTPQI).
> add tests for HW RAID for smartpqi and hpsa testing

- distribution/ltp-upstream/lite/runtest.sh
We are seeing many cve failures after recently adding them back, disableing them while we investigate the failures, see FMK-1271
> disable cve ltp tests

- storage/blk/runtest.sh
> blktests: disable nvme/016 for RHEL7 s390x

- vm/kvm-unit-tests/x86_unittests.cfg
These 2 tests (port80 and vmx_vmcs_shadow_test) are failing with timeout randomly when running with Debug Kernel installed. Increasing the timeout will prevent these failures.
> vm/kvm-unit-tests: Increase the timeout to prevent failures in Debug Kernel testing.

- vm/kvm-self-tests/runtest.sh
As agreed with Thomas Huth will disable the test temporarily until the patch series which contains the fix get merged to the Kernel.
> vm/kvm-self-tests: Disable dirty_log_test since it is failing randomly

- cpu/idle/runtest.sh
- cpu/idle/utils/idle-power-test.sh
Two issues are causing failures.  One is counter rollover.  The
second is that the power utilization improvement on low power
systems does not meet the expectations of this script.  Fix the
first issue by handling rollover fix the second by returning SKIP.
> cpu/idle: resolve failure issues

- storage/dm/common/Makefile
- storage/iscsi/params/Makefile
Fix missing Python dependencies for storage/iscsi/params and storage/dm/common tests.
> Add platform python and devel deps

- cki_lib/libcki.sh
Currently, if cki_set_reason $CKI_FAIL "<msg>" is called before
calling cki_report_result, the <msg> is lost.
For example, insted of outputting:
:: [ 12:26:29 ] :: [   FAIL   ] :: runtest() intel system is running: NONE
The failed test outputs the following:
:: [ 12:22:13 ] :: [   FAIL   ] :: runtest()
Fix this by passing $g_reason_fail when call rlFail from
cki_report_result.
> cki_lib/libcki.sh: make sure output from cki_set_reason is not lost

- distribution/kpkginstall/runtest.sh
When using `grubby --set-default`, the argument must be in the
form of `vmlinuz-KVR` instead of just `KVR`. Without this change,
the kernel won't show up as the primary kernel at boot time. The
originally installed kernel will boot instead.
Also, remove the `/dev/null` redirect so we can see errors from
`grubby` and `zipl` in the future.
Fixes FASTMOVING-1315.
> Use vmlinuz-KVR when using grubby

- storage/blk/runtest.sh
No nvme-cli provided on RHEL-7.5 s390x platform, so disable them.
> blktests: disable nvme/* for RHEL7.5 s390x

- filesystems/xfs/xfstests/known_issues
As the patch series for this test do not go into upstream
stable trees, and have not yet landed into RHEL trees.
Skip it for now, after all fixed we can pull it back.
> fs/xfs/xfstests: skip generic/402 for now

- misc/module-load/modules.rhel8
The cifs module fails to unload with a "FATAL: Module gcm is builtin"
error.  Temporarily remove cifs from modules.rhel8 until RHBZ 1767094
is resolved.
> misc/module-load: temporarily remove cifs from RHEL8

- vm/kvm-unit-tests/runtest.sh
- vm/kvm-unit-tests/x86_unittests.cfg
The QEMU binary is in a different location in Fedora and RHEL, updating the script to account for that.
Also updating the timeout for vmx_vmcs_shadow_test test since it still failed for Debug Kernel.
> vm/kvm-unit-tests: Allow KVM Unit Tests to run on ARK

- ipmi/stress/ipmitool-loop/runtest.sh
On some machines, a warning event may cross the threshold and physically bring down the machines
> Remove ipmi event simulation

- distribution/ltp-upstream/include/knownissue.sh
It's fixed now, so remove from the blacklist to let it run
normally.
> Remove timer_create01 from the blacklist

- packages/selinux-policy/serge-testsuite/runtest.sh
This is a temporary workaround until we figure out what goes wrong on
ppc64le with CKI kernels.
Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
> serge-testsuite: skip bpf test on non-x86_64 arches

- filesystems/xfs/xfstests/known_issues
It's causing false alarm dmesg warning on debug kernel:
BUG: MAX_LOCKDEP_CHAIN_HLOCKS too low!
> fs/xfs/xfstests: skip generic/374

- misc/module-load/modules.rhel8
This reverts commit 196088bcdbffc4b445db47d02d184fbb99a05a3c.
The kmod tool has been updated so it's no longer a fatal error to remove
a built-in driver [*], therefore cifs can be added back into the test.
[*] https://git.kernel.org/pub/scm/utils/kernel/kmod/kmod.git/commit/?id=52a0ba82e1ad
> Revert "misc/module-load: temporarily remove cifs from RHEL8"

- distribution/ltp-upstream/include/Makefile
- distribution/ltp-upstream/include/ltp_log_parser.py
- distribution/ltp-upstream/include/runtest.sh
A simple script `ltp_log_parser.py` is added to fetch failure snippet log, and a function `GetFailureLog()` is also added. Manual test is done, log is saved [here](https://gitlab.cee.redhat.com/huanli/pluto/blob/sandbox2/sandbox/FMK1466/log/03/01.md).
> FMK-1466 Include snippet of LTP failure

- filesystems/xfs/xfstests/Makefile
- filesystems/xfs/xfstests/known_issues
- filesystems/xfs/xfstests/runtest.sh
After we swtich to run tests on debug kernel, it's easy to hit this
warning during dmesg check of beaker by random subcase of xfstests.
xfstests upstream has whitelist this string as it is a false alarm,
not a real issue.
We can't skip subcase which is hitting this warning because any
stressful subcase could hit this. So bring generic/374 back, which
was wrongly skipped when we first hit this warning.
This solution suggested by Rachel should work according to:
https://git.beaker-project.org/cgit/restraint/tree/plugins/report_result.d/01_dmesg_check#n29
Signed-off-by: xiangcai <jencce2002@gmail.com>
> fs/xfs/xfstests: whitelist dmesg string MAX_LOCKDEP_CHAIN_HLOCKS

- ipmi/stress/ipmitool-loop/runtest.sh
IPMI supported checks vary widely depending on bmc implementation, also whether the system has updated firmware. For kernel testing, we want to verify the kernel doesn't get wedged or failures present in the logs, so ignore failures for all ipmi checks in this case.
> Ignore unsupported ipmi checks

- packages/perf/internal-testsuite/runtest.sh
somehow piping to external prg (ex: tee) could cause race condition based on observation/debugging
> save and redirect perf test to log file,

- filesystems/xfs/xfstests/Makefile
- filesystems/xfs/xfstests/runtest.sh
The dmesg falsestrings will now be set in the beginning of each recipe, this will apply to all beaker tasks. The MAX_LOCKDEP_CHAIN_HLOCKS string will be included as a falsestring. The current approach was causing false positives since the defaults were overwritten.
> Revert MAX_LOCKDEP_CHAIN_HLOCKS falsestrings

- jvm/runtest.sh
The Maven call to install dependencies for the jvm test could fail due
to infrastructure problems. In those cases, the test should be aborted
so that infrastructure problems don't end up being marked as test
failures.
> Make the jvm test more robust

- distribution/ltp-upstream/include/knownissue.sh
- distribution/ltp-upstream/lite/patches/disable-btrfs.patch
- distribution/ltp-upstream/lite/runtest.sh
It seems that `fs_fill` is working properly now, so no need to keep it in known issues. The exception seems to be when it runs on btrfs, so disable that filesystem.
> Remove fs_fill from known issues

- distribution/ltp-upstream/include/ltp_log_parser.py
- distribution/ltp-upstream/include/runtest.sh
Enable `distribution/ltp-upstream/lite/runtest.sh` to upload filtered test log to beaker.
> FMK-1466 Include snippet of LTP failure (cont)

- cki_lib/libcki.sh
- distribution/kpkginstall/Makefile
- distribution/kpkginstall/runtest.sh
Older versions of bash don't support certain syntax, update cki_lib to make it compatible for rhel5. Default to yumdownloader command as --download option was added RHEL6 or later.
> Make kpkginstall compatible with RHEL5

- distribution/ltp-upstream/include/knownissue.sh
So the fs_fill was recently patched to skip btrfs however it's still failing upstream kernels, lets disable again while we investigate. See 4063306 for results.
Heads up @emanchado  !
> Disable fs_fill again

- distribution/ltp-upstream/lite/runtest.sh
This commit will pull in potential fix for setrlimit06 by lowering RLIMIT_CPU parameters to speed up testing.
> Update to recent commit for setrlimit06 fix

- example/example.xml
Since we do rely on both beakerLib and restraint-rhts (soon to be removed), we should probably include the expected harness dependencies, will update to restraint vs restraint-rhts once legacy rhts commands
are removed.
> Add harness section for example.xml

- storage/blk/Makefile
I've sent the patch to upstream, but it still not merged.
> blktests: update the blktests repository to fix the compiling issue on RHEL7

- kdump/include/runtest.sh
grubby is not installed by default on F31.
To ensure crash memory is reserved properly on Fedora by updating kernel options by grubby, added a check and install grubby if it's not installed.
Verified on Beaker.
> kdump: Check and install grubby

- example/example.xml
Required for DCI testing, the dependency parameter will be used by the DCI client to mirror the tarball to the jumphost.
> Add dependency url for DCI xml

- trace/ftrace/tracer/ftrace-tracer.sh
Current logic of testing tracer availability can be mis-leading since
wakeup will also match wakeup_rt. It did not bring much hurt because now
wakeup_rt is always enabled with wakeup. However it worth to be fixed.
Reported-by: Philipp Rudo
> ftrace-tracer: Test tracer availability by grep -w

- kselftests/Makefile
- kselftests/README.md
- kselftests/include.sh
- kselftests/runtest.sh
Currently we only support bpf, net, forwarding, tc tests
Signed-off-by: Hangbin Liu <haliu@redhat.com>
> CKI: create a test wrapper for upstream kernel selftest

- kdump/include/runtest.sh
- kdump/kdump-sysrq-c/runtest.sh
1. Allow upgrading Kdump/Crash to latest F32 build
- This would hopefully solve the issue of userspace tools support on upstream kernels.
- Systemd/Dracut will be upgraded along with kexec-tools to avoid any service dependencies.
- Hardcode '--releasever=32' for now 
2. Add 2 options UPGRADE_FC_KDUMP/UPGRADE_FC_CRASH to
enable/disable package upgarding.
- By default, both options are 'true'.
- Kexec-tools/Crash will not be upgraded to F32 build if UPGRADE_FC_KDUMP or UPGRADE_FC_CRASH is set to be false.
- This is just in case any regression introduced in latest F32 userspace builds.
- Applied to FC only.
3. Other minor fixes
- Kdump service is not restarted after reseting the default config
- Check if dmidecode is installed before generating bios log.
- Cleanup vmcores at the end of test …
> kdump: Install crash/kexec-tools from F32

- networking/ipsec/ipsec_basic/ipsec_basic_netns/runtest.sh
Since CKI should be only running basic Tier0/Tier1 sanity level testing,
comment perf_test
Signed-off-by: Xiumei Mu <xmu@redhat.com>
> networking/ipsec: remove throughput test

- networking/tcp/tcp_keepalive/runtest.sh
It's a continuous workaround for bz1755825
after stop firewalld service, sleep for slow host(s390x) or debug kernel
Signed-off-by: Xiumei Mu <xmu@redhat.com>
> sleep after stopping firewalld

- packages/audit/audit-testsuite/runtest.sh
New tests were added recently to audit-testsuite (kernel audit upstream testsuite for audit used by this beaker tests). Two of them are not RHEL-7 compatible and need to be filtered out, they run correctly on RHEL-8.
> Audit testsuite rhel7 fix

- distribution/ltp-upstream/include/knownissue.sh
The fs_fill test will fail periodically on slower machines, the timeout needs to be adjusted, for now skip the test while we experiment with the proper timeout values to avoid this test from failing.
> Add fs_fill to known_issues

- kselftests/include.sh
- kselftests/runtest.sh
We should use env CKI_SELFTEST_URL as the download URL.
If not found, the test should skip instead of warn.
Signed-off-by: Hangbin Liu <haliu@redhat.com>
> kselftest: use CKI_SELFTEST_URL

- networking/ipsec/ipsec_basic/ipsec_basic_netns/runtest.sh
Current sleep time is not enought on some slow machines like s390x,
so sleep double time.
> ipsec_baisc_netns: sleep longer for slow machines

- distribution/ltp-upstream/lite/Makefile
- distribution/ltp-upstream/lite/hugetlb.inc
- distribution/ltp-upstream/lite/runtest.sh
This is mainly for getting rid of errors like:
mem.c:822: BROK: nr_hugepages = 415, but expect 512
And also involves 'mem_low_mode' to avoid reporting false-positive(like memleak causes above error).
> ltp: setup nr_hpage for hugetlb if MemAvailable is low

- storage/hba/san-device-stress/Makefile
- storage/hba/san-device-stress/main.sh
- Remove extraneous lines from Makefile
- refactor main.sh  - simplify install_fio function as it is not necessary to install from source
- change FIO tests to use libaio and also perform data verification
- simplify the code to find non-boot disks suitible for generating I/O
> Refactor san-device-stress-test

- storage/hw_raid/Makefile
-unnecessary to require hw_raid in Makefile as it is a circular dependency
> Remove invalid line from Makefile

- distribution/ltp-upstream/include/knownissue.sh
The failed test cases (`ksm03, ksm03_1, ksm04 and ksm04_01`) are due to https://github.com/linux-test-project/ltp/issues/611.
> FASTMOVING-1161 ltp ksm failure

- kselftests/Makefile
Remove PURPOSE as we don't have this file. Add include.sh and README.md.
Signed-off-by: Hangbin Liu <haliu@redhat.com>
> kselftests: update Makefile files

- distribution/ltp-upstream/include/knownissue.sh
- distribution/ltp-upstream/lite/Makefile
- distribution/ltp-upstream/lite/runtest.sh
This shortage memory issue has been solved by:
commit afe63f3500c1 (ltp: setup nr_hpage for hugetlb if MemAvailable is low)
So let's move hugetlb tests out of the blacklist.
> ltp/knownissue: enable hugetlb test in CKI-ltp

- tracepoints/operational/runtest.sh
Known issue where iocost:iocost_ioc_vrate_adj fails to compile for Tracepoints test, skip this test for now until BZ 1824812 is resolved.
> Tracepoints: skip iocost_ioc_vrate_adj probe

- autofs/connectathon/runtest.sh
- networking/common/include.sh
- networking/route/pmtu/common/include.sh
- networking/route/route_func/common/include.sh
- networking/tunnel/geneve/basic/runtest.sh
- networking/tunnel/gre/basic/runtest.sh
- networking/tunnel/l2tp/basic/runtest.sh
- networking/tunnel/vxlan/basic/runtest.sh
- networking/vnic/ipvlan/basic/runtest.sh
Verify current restraint provides rstrnt-sync-* functionality: 
*rpm -ql restraint-0.2.0-1.el7bkr.x86_64|grep rstrnt-sync
/usr/bin/rstrnt-sync
/usr/bin/rstrnt-sync-block
/usr/bin/rstrnt-sync-set
Time to update legacy  rhts-sync with client-server restraint functionality.
> update legacy rhts-sync- to rstrnt-sync-

- distribution/ltp-upstream/include/knownissue.sh
This test which is run right after podman tests is using cgroup1
which differs from podman test which uses cgroup2, mixing the two
can cause bad side effects, see the following issue request for more
details.
https://github.com/linux-test-project/ltp/issues/611
> Disable kms02 for upstream kernels

- filesystems/loopdev/sanity/Makefile
- filesystems/xfs/xfstests/xfstests-run.sh
- filesystems/xfs/xfstests/xfstests-setup.sh
With another commit to print more debug info for xfstests.
> loopdev/sanity: fix gcc10 build error

- kdump/include/runtest.sh
- kdump/kdump-sysrq-c/runtest.sh
- kdump/kexec-boot/runtest.sh
- Installing/Upgrading kexec-tools in kexec-boot if Fedora
- Rename PrepareKdump() to SetupKdump()
- Move installing/upgrading kexec-tools pkgs from SetupKdump to PrepareKdump
> kdump: Fix kexec-tools installation kexec-boot test

- kdump/include/runtest.sh
File $K_REBOOT was wrongly cleared in RestoreKdumpConfig().
It will cause system reboot loop when KER1ARGS passed to the test requiring an extra reboot for changing boot loader.
> kdump: Test restore shouldn't clear reboot flag

- distribution/ltp-upstream/include/knownissue.sh
- distribution/ltp-upstream/lite/runtest.sh
* Update LTP to a recent commit to pull in hugetlbfs fixes
* Add bpf/s390x failures to known issues file
* Miscellaneous cleanup for known issues file
* Remove pty04, move_pages12, and connect02 from known issues
> Update LTP to recent commit

- kdump/include/runtest.sh
Since base compose now is Fedora-32, pull latest kdump/crash packges from F-33.
> kdump: Pull latest kdump/crash from F33
