distribution/kpkginstall/runtest.sh
Booting aarch64 servers with the standard, generic vmlinux binary
causes the "invalid magic number" error and prevents the server
from booting.
Strip the generic binary so that it boots on aarch64 and compress
it into a vmlinuz. Remove the generic vmlinux afterwards.
=> aarch64: Strip vmlinux and make vmlinuz

distribution/kpkginstall/runtest.sh
=> s390: Save kernel image as vmlinuz

distribution/ltp/include/runtest.sh
=> LTP - remove check for TESTPATH when submitting logs

distribution/ltp/lite/RHELKT1LITE.20180515
=> LTP: disable move_pages12 temporarily

distribution/kpkginstall/runtest.sh
=> kpkginstall: fix installation of recent s390x kernels

distribution/kpkginstall/runtest.sh, distribution/ltp/lite/runtest.sh
TODO: write up a readme or something to mention the expectations
=> Make tests adhere to standards we have

README.md
=> README: clarify the text and mention test requirements

distribution/kpkginstall/runtest.sh
Instead of requiring the KVER parameter being passed through the
environment in distribution/kpkginstall, extract the kernel version from
the kernel image filename in the tarball.
This simplifies the interface and workings of kpet, so that it only has
to deal with a tarball, and doesn't have to know which kernel version
it's dealing with.
=> kpkginstall: Stop requiring KVER parameter

distribution/ltp/lite/RHELKT1LITE.20180515
@veruu or @spbnick please review
=> mtest06 fails with exit code 1 and no output

distribution/kpkginstall/runtest.sh
=> revert back to grubby

distribution/plugins/report_result.d/01_dmesg_check
=> hacked up 01_dmesg_check to filer out failures

memory/function/memfd_create/Makefile, memory/function/memfd_create/PURPOSE, memory/function/memfd_create/_env, memory/function/memfd_create/runtest.sh, memory/function/memfd_create/t_get_seals.c, memory/function/memfd_create/t_memfd_create.c
New memory test to on-board to CKI
=> Initial commit of memfd_create test

vm/kvm-unit-tests/runtest.sh, vm/kvm-unit-tests/unittests.cfg
This will enable more tests, update to a later version, and add support for aarch64
=> kvm-unit-tests updates

storage/lvm/thinp/sanity/Makefile, storage/lvm/thinp/sanity/PURPOSE, storage/lvm/thinp/sanity/runtest.sh
Initial commit to move thinp_sanity test upstream
=> initial commit of thinp_sanity test

misc/amtu/README.md
add Readme for amtu test suite
=> Add readme for amtu

vm/kvm-unit-tests/runtest.sh
Fix for FASTMOVING-484, check test can be run on aarch64 or not.
=> Minor update for kvm-unit-tests to support aarch64

vm/kvm-unit-tests/runtest.sh
This is a follow on to @idorax PR, additional changes needed for ARM testing
=> don't check the kernel options on ARM

filesystems/loopdev/sanity/Makefile
Minor update to fix lookaside variable to only point to upstream location
=> fix lookaside for upstream

networking/driver/sanity/Makefile, networking/driver/sanity/README.md, networking/driver/sanity/runtest.sh
@veruu can you please review ? I'll send a test job separately.
=> initial commit of network driver sanity test

standards/usex/1.9-29/README.md
add readme for usex test suite
=> Add readme for usex

filesystems/loopdev/sanity/Makefile
The basic unit testing is done, please refer to: http://pastebin.test.redhat.com/711894
=> remove LOOKASIDE_BOS as it is useless

README.md
Add back root README.md, which got delete by mistake.
=> add back root readme

storage/lvm/thinp/sanity/README.md
=> Thinpsanity readme

distribution/kpkginstall/runtest.sh
Luckily we have not ran on older releases yet...
=> Use variable instead of "dnf"

distribution/kpkginstall/runtest.sh
=> Remove repo skipping from RPM install

distribution/kpkginstall/runtest.sh
=> fixup kver quoting

distribution/kpkginstall/runtest.sh
The original code wasn't setting YUM var. after reboot. Let's fix that.
=> set YUM when necessary

distribution/kpkginstall/runtest.sh
=> Add arch to extracted version

packages/redhat-rpm-config/kabi-whitelist-not-found/Makefile, packages/redhat-rpm-config/kabi-whitelist-not-found/PURPOSE, packages/redhat-rpm-config/kabi-whitelist-not-found/runtest.sh
hi @veruu can you please review :-) sample job in the ticket, I'll let kpet-db CI test it everywhere.
=> initial commit of kabi-whitelist-not-found

packages/i2c-tools/sanity/i2cdetect-smoke/Makefile, packages/i2c-tools/sanity/i2cdetect-smoke/PURPOSE, packages/i2c-tools/sanity/i2cdetect-smoke/README.md, packages/i2c-tools/sanity/i2cdetect-smoke/runtest.sh
requesting PR for i2c detect sanity test
=> inital commint of i2c sanity test

packages/httpd/mod_ssl-smoke/Makefile, packages/httpd/mod_ssl-smoke/PURPOSE, packages/httpd/mod_ssl-smoke/README.md, packages/httpd/mod_ssl-smoke/run_postinstall_script.py, packages/httpd/mod_ssl-smoke/runtest.sh
@veruu  and @rasibley 
Please review mod_ssl  test initial commit PR
=> initial commit of mod_ssl smoke test

packages/selinux-policy/serge-testsuite/Makefile, packages/selinux-policy/serge-testsuite/PURPOSE, packages/selinux-policy/serge-testsuite/runtest.sh
=> initial commit of serge-testsuite

packages/audit/audit-testsuite/Makefile, packages/audit/audit-testsuite/PURPOSE, packages/audit/audit-testsuite/README.md, packages/audit/audit-testsuite/runtest.sh
@veruu 
Please review  audit-testsuite PR request.
=> inital commit of audit-testsuite

vm/kvm-unit-tests/README.md
@spbnick 
Please review PR for  kvm-unit-test readme.
=> Add kvm-unit-test readme

kdump/include/Makefile, kdump/include/PURPOSE, kdump/include/runtest.sh, kdump/kdump-sysrq-c/Makefile, kdump/kdump-sysrq-c/PURPOSE, kdump/kdump-sysrq-c/runtest.sh
It tests
1) crashkernel memory reservation
2) kdump service startup
3) Vmcore saving after a system panic
=> kdump: Add a kdump-sysrq-c test

misc/amtu/Makefile
=> add @development to Makefile

distribution/ltp/include/knownissue.sh
=> ltp/include: mask mount02 failure on upstream kernel

memory/function/memfd_create/README.md
@spbnick 
Please review memfd_create test readme  PR.
=> add readme for memfd_create test

vm/hugepage/libhugetlbfs/README.md
@spbnick 
Please review libhugetlbfs test readme PR.
=> add libhugetlbfs test readme

stress/stress-ng/Makefile, stress/stress-ng/PURPOSE, stress/stress-ng/README.md, stress/stress-ng/runtest.sh
@veruu ,
Please review the PR
Thanks,
=> initial commit of stress-ng test

stress/stress-ng/runtest.sh
@rasibley , and @veruu 
Discuss with Test-maintainer and agree  that stress-ng is "pass" when returns with exit: 0,2,3, 
and  adding  two tests:fnctl/kcmp to   rhel7 ppc64  RHEL specific excludes.
=> update stress-ng test:  pass when returns exit: 0,2,3  and exclude  two tests for rhel7 ppc64 

rt-tests/include/Makefile, rt-tests/include/runtest.sh, rt-tests/rt_migrate_test/Makefile, rt-tests/rt_migrate_test/runtest.sh, rt-tests/rteval/Makefile, rt-tests/rteval/PURPOSE, rt-tests/rteval/runtest.sh, rt-tests/sched_deadline/Makefile, rt-tests/sched_deadline/runtest.sh, rt-tests/smidetect/Makefile, rt-tests/smidetect/PURPOSE, rt-tests/smidetect/runtest.sh
Follow our documents, all the test passed by beaker [1].
And for "suggestion pattern", because the rt kernel is another flavour for rhel kernel. So we have no special "pattern" for rt kernel.
[1] https://beaker.engineering.redhat.com/jobs/3424443
=> Add RT related cases to CKI testing.

distribution/kpkginstall/runtest.sh
=> We need to set package name after reboot again

distribution/kpkginstall/runtest.sh
Yeah, if dnf had consistent behaviour when redirected to a file and
being piped, that would be great.
=> Only checkfirst match

distribution/kpkginstall/runtest.sh
https://bugzilla.redhat.com/show_bug.cgi?id=584525
No more comments needed.
=> Fixup yum/dnf mess

vm/kvm-self-tests/Makefile, vm/kvm-self-tests/README.md, vm/kvm-self-tests/patches/bitmap.h.patch, vm/kvm-self-tests/runtest.sh
There is a case 'dirty_log_test' failing to be built, I just comment it out for the time being.
=> Enable kvm self tests

distribution/ltp/include/knownissue.sh
=> ltp/include: enlarge the skipping scope for request_key04

distribution/ltp/include/knownissue.sh
=> ltp/include: mask keyctl02 failures on rhel8

storage/blk/Makefile, storage/blk/runtest.sh
Signed-off-by: Yi Zhang <yizhan@redhat.com>
=> disable loop/001 for upstream 5.0.0

distribution/ltp/include/knownissue.sh
=> ltp/include: extend fanotify09 skipping range

storage/blk/runtest.sh
=> blktests: disable loop/001 for linux-5.0

networking/route/pmtu/Makefile
@veruu please review, this should resolve RT failures
=> enable kernel-rt-modules-extra in Makefile

storage/blk/runtest.sh
=> blktests: update the existing status

distribution/kpkginstall/runtest.sh
=> kpkginstall: More verbose, use tee consistently

distribution/kpkginstall/runtest.sh
This continues work on FASTMOVING-591.
This patch does following:
* If a kernel download fails, it's likely an infrastructure issue, so we
want to report warn/aborted.
* If a kernel package fails to install after being downloaded, it's
likely a distro issue, so we abort the recipe as well, but report fail
instead.
=> separate kernel installation and download

packages/audit/audit-testsuite/Makefile, packages/audit/audit-testsuite/runtest.sh
Test-maintainer updates  test repo to stabilze  audit-testsuite.
Pull from test repo and open this PR to reflect code changes.
=> Stabilize audit-testsuite

packages/perf/internal-testsuite/Makefile, packages/perf/internal-testsuite/runtest.sh
Copying @jbastian PR :-) @veruu this will mask the panic for perf test.
=> skip on mustangs until bz1619305 is resolved

legacy/pci_id/02-pci-id.sh, legacy/pci_id/Makefile, legacy/pci_id/README.md, legacy/pci_id/runtest.sh, legacy/shared/file-utils.sh, legacy/shared/kernel-ci.sh, legacy/shared/ksymbols.sh, legacy/shared/rpm-utils.sh, legacy/shared/vmlinuz.sh, legacy/whitelist/01-whitelist.sh, legacy/whitelist/Makefile, legacy/whitelist/README.md, legacy/whitelist/runtest.sh
=> Add PCI ID and kABI Whitelist symbol removal checks.

networking/tcp/tcp_keepalive/Makefile, networking/tcp/tcp_keepalive/PURPOSE, networking/tcp/tcp_keepalive/README.md, networking/tcp/tcp_keepalive/keepalive.c, networking/tcp/tcp_keepalive/runtest.sh
Porting network tcp keepalive test.
=> ported networking tcp keepalive test

storage/blk/runtest.sh
=> blktests: disable block/002 for RHEL8

networking/common/include.sh
@veruu one minor change to common lib, please review
=> set permissions properly for all net tools

networking/udp/udp_socket/Makefile, networking/udp/udp_socket/PURPOSE, networking/udp/udp_socket/README.md, networking/udp/udp_socket/runtest.sh, networking/udp/udp_socket/udp_no_check.c, networking/udp/udp_socket/udp_socket.c
Don't know PACKAGE_NAME is required. Looks it is optional from [1], if it is true, I'll remove it from Makefile, please help to review and confirm.
- [1] https://beaker-project.org/docs/user-guide/task-metadata.html
=> Port 'kernel/networking/udp/udp_socket' to github (#819)

storage/blk/runtest.sh
=> blktests: disable block/017 on s390x

legacy/pci_id/Makefile, legacy/shared/Makefile, legacy/shared/runtest.sh, legacy/whitelist/01-whitelist.sh, legacy/whitelist/Makefile
=> legacy: Fix dependency issues

storage/blk/runtest.sh
=> blktests: update block/002 block/017 filter method

networking/socket/fuzz/Makefile, networking/socket/fuzz/PURPOSE, networking/socket/fuzz/README.md, networking/socket/fuzz/common.c, networking/socket/fuzz/func.c, networking/socket/fuzz/func.h, networking/socket/fuzz/help.c, networking/socket/fuzz/metadata, networking/socket/fuzz/network.h, networking/socket/fuzz/proto.h, networking/socket/fuzz/runtest.sh, networking/socket/fuzz/sctp.c, networking/socket/fuzz/setopt.c, networking/socket/fuzz/setopt.h, networking/socket/fuzz/socket.c, networking/socket/fuzz/subtest.yml, networking/socket/fuzz/tcp.c, networking/socket/fuzz/todo, networking/socket/fuzz/udp.c
Hi @veruu please review, test jobs in the ticket.
=> initial commit of socket_fuzz test

networking/tunnel/vxlan/basic/Makefile, networking/tunnel/vxlan/basic/PURPOSE, networking/tunnel/vxlan/basic/README.md, networking/tunnel/vxlan/basic/metadata, networking/tunnel/vxlan/basic/runtest.sh, networking/tunnel/vxlan/basic/subtest.yml
=> initial commit of vxlan basic test

storage/scsi/vpd/Makefile, storage/scsi/vpd/PURPOSE, storage/scsi/vpd/README.md, storage/scsi/vpd/main.sh, storage/scsi/vpd/runtest.sh
add storage/scsi/check-scsi-vpd  for cki, please have a look if can be merged
=> add scsi case check-scsi-vpd

networking/tunnel/gre/basic/Makefile, networking/tunnel/gre/basic/PURPOSE, networking/tunnel/gre/basic/README.md, networking/tunnel/gre/basic/metadata, networking/tunnel/gre/basic/runtest.sh, networking/tunnel/gre/basic/subtest.yml
Port networking tunnel GRE basic  to CKI test-beaker.
=> port tunnel gre basic test

networking/ipsec/ipsec_basic/ipsec_basic_netns/runtest.sh
hi @veruu please review, syncing the downtream copy with upstream to help stabilize against upstream kernels.
=> add sleep after send data

tracepoints/operational/Makefile, tracepoints/operational/PURPOSE, tracepoints/operational/README.md, tracepoints/operational/runtest.sh
Port Systemtap Tracepoint Operational Test
=> port tracepoint operational test

storage/swraid/trim/PURPOSE, storage/swraid/trim/README.md, storage/swraid/trim/main.sh
Since rhel7's support for MD write-journal RAID is unstable, temporarily delete the journal raid part.
please take a look.
beaker job id: 6963820
=> Update the test case because system hit panic when testing RHEL7

filesystems/nfs/connectathon/runtest.sh
=> rhel4 is no longer supported

storage/lvm/thinp/sanity/Makefile
=> Use cached version of iozone3

packages/selinux-policy/serge-testsuite/runtest.sh
Update to match internal commit 668b5c3f2.
Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
=> serge-testuite: sync with downstream

distribution/ltp/lite/configs/RHELKT1LITE.20190115
@major temp work around while we work on updating ltp to next release for F30
=> disable setrlimit03 until ltp is updated to 20190517

jvm/Makefile, jvm/PURPOSE, jvm/README.md, jvm/runtest.sh
hi @veruu can you please review ? I'll include test jobs in the ticket.
=> initial commit of jvm tests

kdump/include/runtest.sh, kdump/kdump-sysrq-c/runtest.sh
Added steps to validate a vmcore captured after a sysrq-c panic by crash utitlies.
To run crash against a vmcore, it requires to install crash and kernel-debuginfo/kernel-debuginfo-common packages. kernel-debuginfo/kernel-debuginfo-common will be installed from kernel-cki repo.
=> kdump-sysrq-c: Analyze a vmcore by crash utilities

pciutils/update-pciids/Makefile, pciutils/update-pciids/PURPOSE, pciutils/update-pciids/README.md, pciutils/update-pciids/runtest.sh
Porting pciutils update pci ids test.
=> Porting pciutils update-pciids test

storage/blk/Makefile, storage/blk/runtest.sh
=> blktests: add nvme test cases

kernel/bpf/test_bpf/Makefile, kernel/bpf/test_bpf/PURPOSE, kernel/bpf/test_bpf/README.md, kernel/bpf/test_bpf/metadata, kernel/bpf/test_bpf/runtest.sh, kernel/include/install.sh
=> Add test_bpf

power-management/cpupower/sanity/Makefile, power-management/cpupower/sanity/PURPOSE, power-management/cpupower/sanity/README.md, power-management/cpupower/sanity/runtest.sh, power-management/cpupower/sanity/utils/cpupower_sanity_test.sh
Manual tests are done on both KVM and bare metal, please refer to test log:
* http://pastebin.test.redhat.com/783840
=> Port test case 'power-management/cpupower/sanity' (#1017)

container/podman/runtest.sh
=> Multi-arch support for podman system tests

storage/blk/runtest.sh
=> blktests: add more filters for nvme test case

storage/swraid/trim/main.sh
Signed-off-by: zhongchanghui <czhong@redhat.com>
Hello,Rachel
i have fixed fstrim error in rhel7,please have a look and merge this PR.
Thanks
=> fix error for fstrim RAID0 in RHEL7

storage/swraid/common/libmdadm.sh, storage/swraid/trim/main.sh
Hello
I have fixed the error "write error: No space left on device" on kernek-5.2
Thanks
=>  fix error "write error: No space left on device" on kernel-5.2

storage/include/libstqe.sh
Use python2 on RHEL-7 even if python3 is installed and use version of pip based on Python version.
Signed-off-by: Filip Suba <fsuba@redhat.com>
=> Fix: Use python on RHEL-7 even if python3 is installed and use correct version of pip

vm/kvm-unit-tests/runtest.sh
Merge the logs in one file to facilitate triage and log consolidation.
=> vm/kvm-unit-tests: Merge the logs of individual tests in a single file (tests_run.log).

packages/tuned/basic/Makefile, packages/tuned/basic/PURPOSE, packages/tuned/basic/README.md, packages/tuned/basic/lib.sh, packages/tuned/basic/metadata, packages/tuned/basic/runtest.sh, packages/tuned/tune-processes-through-perf/metadata, packages/tuned/tune-processes-through-perf/runtest.sh
Porting tuned basic common library that used by tuned_perf test.
=> add tuned basic library

container/podman/runtest.sh
Per BZ 1734799, metacopy must be removed from the list of mount options
when running podman system integration tests on RHEL 8.
=> Disable metacopy on RHEL8 for podman

cpu/common/libbkrm.sh
Currently `main()` in `libbkrm.sh` returns $rc which will cause beaker task is marked as 'Aborted' if `runtest()` fails. Hence, `main()` is updated to always return 0, and two status code (`BKRM_STATUS_COMPLETED`  and `BKRM_STATUS_ABORTED`) are defined. BTW, `rhts-abort -t recipe` is removed from rlAbort() after reading the [manual page of rhts-abort](https://beaker-project.org/docs/user-guide/task-environment.html#commands) , please correct me if my understanding is not right.
=> Make sure beaker task is not marked as 'Aborted' if test fails

kdump/include/runtest.sh
In Fedora, kdump is not installed and enabled by default. 
So added steps to 
1) Install kexec-tools and enabled kdump service.  
2) Configure default crashkernel memory
Test passed on Fedora30.
=> kdump: install and config kexec-tools for Fedora

trace/bpf/test_bpf/runtest.sh
=> trace/bpf: Replace rlRpmDownload with $yum download

networking/common/src/mtools/mdump.c, networking/common/src/mtools/mpong.c, networking/common/src/mtools/msend.c
Add necessary C files used by multicast test
1. networking/common/src/mtools/mdump.c
1. networking/common/src/mtools/msend.c
1. networking/common/src/mtools/mpong.c
=> FMK-1034 : Enable /kernel/networking/vnic/ipvlan/basic test in kpet-db (cont)

distribution/ltp-upstream/include/Makefile, distribution/ltp-upstream/include/PURPOSE, distribution/ltp-upstream/include/knownissue.sh, distribution/ltp-upstream/include/kvercmp.sh, distribution/ltp-upstream/include/metadata, distribution/ltp-upstream/include/runtest.sh, distribution/ltp-upstream/lite/Makefile, distribution/ltp-upstream/lite/PURPOSE, distribution/ltp-upstream/lite/runtest.sh
@wangli5665 and @jstancek can you please review when you have a moment? This PR is about fetching the unpatched vanilla version of LTP directly from github to be tested with ark/upstream kernels, for more details and list of known issues so far, please see the internal FMK jira ticket I tagged you in. Issues are tracked with TBD until they are identified as either known or new issues against LTP or the kernel. Thank you !
=> initial commit of ltp upstream

trace/bpf/test_bpf/runtest.sh
=> trace/bpf: Improve support for debug kernel

distribution/kpkginstall/runtest.sh
=> Emojis in kpkginstall failures

distribution/kpkginstall/runtest.sh
The `shellcheck` linter stronly recommends checking for command success
and failure directly in the `if/else` statement itself rather than checking
for `$?`. It requires less code and allows us to easily print some
success output with emojis.
⚠️ **Requires https://github.com/CKI-project/tests-beaker/pull/344 to merge first!**
=>  Check command success directly in if/else

cki_lib/lib.sh, distribution/kpkginstall/Makefile, distribution/kpkginstall/runtest.sh
Reduce repeated code by consolidating all of the failure handling in a
single function that has emojis.
:warning: **Requires #344 and #345 to merge first!**
=> Use abort_recipe() for failures

cki_lib/lib.sh, distribution/kpkginstall/runtest.sh
=> Fix bugs from abort_recipe PR

distribution/kpkginstall/runtest.sh
Getting package names from the repository packages is problematic. Most
pipeline jobs have a `package_name` variable that can be passed via
`KPKG_URL`.
These variables can be passed in the URL after a pound sign `#` and
parsed by kpkginstall.
We can now handle URLs like these:
*  example.com/job/123/repo/#package_name=kernel-rt&amp;debug=yes
:warning: **Requires #346 to merge first.**
=>  Get package name/debug from KPKG_URL variables

networking/macsec/sanity_check/runtest.sh
Fei Liu helped to provide the patch, please review, thanks!
=> Disable case "masec between 2 netns" because system panicked due to bz1745880

tracepoints/operational/Makefile, tracepoints/operational/runtest.sh
@major can you review ? I decided to remove that code since it's installed by default as part of kpginstall, otherwise the harness will install it from the Makefile. See beaker ID 3769092 for test results.
=> install the right kernel-devel for running kernel

networking/tunnel/l2tp/basic/Makefile, networking/tunnel/l2tp/basic/runtest.sh, networking/tunnel/l2tp/basic/subtest.yml
=> Add basic l2tp test

cpu/die/utils/verify-x86-die-support.sh
The script was failing on some systems as it was using the wrong
numa index to compare die cpus to numa data.
=> cpu/die: fix bug in numa node comparison logic

filesystems/general/pjd-fstest/Makefile, filesystems/general/pjd-fstest/PURPOSE, filesystems/general/pjd-fstest/README.md, filesystems/general/pjd-fstest/runtest.sh
Initial porting for pjd-fstest (ext3/ext4/xfs)
=> initial porting pjd-fstest

cpu/die/utils/verify-x86-die-support.sh
As it turns out the index of numa node information provided by
lscpu is not determinate.  So instead, we can verify the numa
node data on a per index basis.
Secondarily, the calculation of logical die count didn't
always work correctly.  Instead of trying to determine if this
system is a beaker system, always check dmesg first and if no
information is available, check /var/log/messages.
=> cpu/die: fix numa comparison

vm/kvm-unit-tests/runtest.sh
This check is aborting several runs according to Veronika. I'm still investigating why the flag is not set correctly in some systems, while I investigated I'm disabling the check to prevent further abortions.
=> vm/kvm-unit-tests: Disable aborting of tests by the nested Flag.

distribution/ltp/openposix_testsuite/Makefile, distribution/ltp/openposix_testsuite/metadata, networking/igmp/conformance/Makefile, networking/igmp/conformance/runtest.sh, networking/route/pmtu/Makefile, networking/route/pmtu/runtest.sh, networking/sctp/auth/sockopts/Makefile, networking/sctp/auth/sockopts/runtest.sh, networking/tcp/tcp_keepalive/Makefile, networking/tcp/tcp_keepalive/runtest.sh, networking/tunnel/geneve/basic/Makefile, networking/tunnel/geneve/basic/metadata, networking/tunnel/geneve/basic/runtest.sh, networking/tunnel/gre/basic/Makefile, networking/tunnel/gre/basic/metadata, networking/tunnel/gre/basic/runtest.sh, networking/tunnel/vxlan/basic/metadata, networking/tunnel/vxlan/basic/runtest.sh, packages/perf/internal-testsuite/Makefile, packages/perf/internal-testsuite/runtest.sh, packages/perf/perftool-testsuite/Makefile, packages/perf/perftool-testsuite/runtest.sh, pciutils/sanity-smoke/Makefile, pciutils/sanity-smoke/runtest.sh, pciutils/update-pciids/Makefile, pciutils/update-pciids/runtest.sh
@veruu or @emanchado can you please review ? Note for openposix kernel-rt-devel is installed by default for RT jobs so it's not required to yum install. See J:3811529 for test results.
=> Add condition when installing RT dependencies

vm/kvm-self-tests/runtest.sh
Add support to run the s390x tests.
=> vm/kvm-self-tests: Enable s390x arch tests

cpu/driver/runtest.sh
On some older intel systems the intel_pstate driver is not supported.
We expect those systems to be running acpi-cpufreq.  Avoid returning
FAIL in those cases.
=> cpu/driver: handle older intel systems which do not have pstate support

storage/hw_raid/main.sh
Change rhts-reboot to simple reboot in kexec_boot_graceful function. Add new fucntion to remove BootNext if set after tests are run.
=> fix reboot problem with EFI based systems

distribution/ltp-upstream/lite/runtest.sh
=> Update LTP commit

storage/hba/san-device-stress/main.sh
Signed-off-by: lilin <lilin@redhat.com>
=> [storage/hba] add FIO regression testing for HBA

filesystems/loopdev/sanity/README.md, filesystems/nfs/connectathon/README.md
Add readme for loop device and nfs connectathon.
=> add readme file

container/podman/runtest.sh
* Use the new bats package from Fedora 31
* Add a multi-arch wrapper for non-x86_64 systems
* Ensure 110-history test uses default container image
* Switch to prettier bats output option
* Add emojis, because why not? 🥰
[test beaker]
=> FASTMOVING-1442: Fix ppc64le podman test errors

ipmi/stress/driver/runtest.sh, ipmi/stress/ipmitool-loop/runtest.sh
Updated both ipmi tests to run for both aarch64 and powerpc systems, depending on the ipmi implementation some commands and drivers are not available, tweaked the test to be more forgiving in these situations. Also to skip properly for systems which are not IPMI capable. The powerpc systems do not use dmidecode, however all bare metal powerpc systems are ipmi capable so we can ignore this check.
=> enable ipmi for aarch64 and power

distribution/ltp-upstream/include/knownissue.sh, distribution/ltp-upstream/lite/runtest.sh
The patch was merged in LTP upstream, update the commit and remove the work around.
https://github.com/linux-test-project/ltp/commit/1bb9f8eff72571320f2a7d6418f66498b510f09f
See J:3910224 for a test job.
=> Remove pivot_root01 from knownissues

ipmi/stress/driver/runtest.sh, ipmi/stress/ipmitool-loop/runtest.sh
I had some ugly indentation, just a few minor udates to clean it up.
=> Make IPMI tests pretty, fix indenting

ipmi/stress/ipmitool-loop/runtest.sh
@veruu can you review? :woman_facepalming:  See J:3913371 for results.
=> add missing space to fix syntax error

distribution/ltp-upstream/include/knownissue.sh, distribution/ltp-upstream/lite/runtest.sh
Update known issues which have since been resolved, also update to a recent commit. 
See FMK-1508 for example beaker jobs and discussion.
=> update ltp to recent commit

firmware/include/Makefile, firmware/include/PURPOSE, firmware/include/README.md, firmware/include/patches/0001-build-do-not-use-Werror.patch, firmware/include/patches/0002-fwts-fix-access_ok-for-the-RHEL8-kernel.patch, firmware/include/runtest.sh, firmware/user-specified/Makefile, firmware/user-specified/PURPOSE, firmware/user-specified/README.md, firmware/user-specified/runtest.sh
There are two tests:
* firmware tests library under include.
* main firmware test suites under user-specified.
=> Initial porting firmware test suites.

distribution/ltp-upstream/lite/runtest.sh
@emanchado  can you review, we need to pull in one more fix, see 4061587 for test results.
=> update ltp to latest commit

example/example.xml
Add an example xml snippet for running LTP, this can be used as a base template for tests which run in beaker.
=> Add example xml running LTP

jvm/dacapobench/runtest.sh, storage/lvm/thinp/sanity/Makefile
@veruu can you please review, see J:4091777 for test results.
=> Update lookaside location for iozone3 and dacapo artifacts

filesystems/xfs/xfstests/Makefile, filesystems/xfs/xfstests/dep-install.sh, filesystems/xfs/xfstests/devices.sh, filesystems/xfs/xfstests/install.sh, filesystems/xfs/xfstests/misc.sh, filesystems/xfs/xfstests/runtest.sh, filesystems/xfs/xfstests/xfstests-preset.sh, filesystems/xfs/xfstests/xfstests-run.sh, filesystems/xfs/xfstests/xfstests-setup.sh
For the convenience of debug if something goes wrong.
=> fs/xfs/xfstests: add some debug output info

cki_lib/Makefile
Add Makefile skeleton to cki_lib.
=> Add Makefile to cki_lib

packages/audit/audit-testsuite/runtest.sh
Signed-off-by: Ondrej Moris <omoris@redhat.com>
=> audit-testsuite: bpf only for F>31 and RHEL>8.1

storage/hw_raid/main.sh
I simplified the install_fio function to prevent warnings.
=> change fio_install function

firmware/include/patches/0001-build-do-not-use-Werror.patch, firmware/include/patches/0002-fwts-fix-access_ok-for-the-RHEL8-kernel.patch, firmware/include/runtest.sh
Set fwts version to V20.03.00 and update bundled patches.
=> firmware/include update V20.03.00 and fixes

distribution/ltp-upstream/include/knownissue.sh, distribution/ltp-upstream/lite/runtest.sh
For this LTP update, we have the following changes:
* Update to recent commit
* Include add_key05 to known issues
=> Update LTP to a recent commit

distribution/ltp-upstream/include/knownissue.sh
GitHub issue #611 also affects ksm02_1 as well, include this in the knownissues file.
=> Include ksm02_1 to known issues for GitHub issue #611

kselftests/Makefile, kselftests/include.sh, kselftests/runtest.sh
This patchset fixed selftest URL typo and skip the test if not find.
I also fixed a parameter issue in include file.
=> Kselftest update

kdump/include/runtest.sh, kdump/kexec-boot/PURPOSE, kdump/kexec-boot/metadata, kdump/kexec-boot/runtest.sh
This is a new kdump test to test kexec load and reboot.
=> kdump: Add new kexec load test

packages/libkcapi/af_alg-test/runtest.sh
Explanations are in the commit messages.
=> Minor libkcapi test improvements

distribution/kpkginstall/runtest.sh
see separate commits for explanation
=> WIP: kpkginstall fixes
